### ISSUE TITLE
vlans role

### ISSUE THREAD

**Issue by privateip** [ansible-network/network-proposals#2]
# Proposal: vlans role

*Author*: Peter Sprygada <@privateip>

*Date*: 2018-10-09

- Status: New
- Proposal type: role
- Targeted release: new
- Associated PR: none
- Estimated time to implement: 1 day

## Motivation
This proposal describes  the implementation of a VLANs role to replace the current platform agnostic implementation of`net_vlan` currently in Ansible core.  

NOTE: This role will supersede https://github.com/ansible-network/configure-vlan

### Problems
The current module is difficult to maintain and even more challenging to extend.  By moving the module functionality to a role, platform specific implementations will be greatly simplified.

#### Functions
- main.yaml
  noop by default
- configure.yaml
  Perform all configuration activities

#### Model

```yaml
vlans:
  operation: { default: merge, choices: [merge, replace, override] }
  config:
    - vlan_id: { type: int }
      name: { type: str }
      status: { default: active, choices: [active, suspend] }
      state: { default: present, choices: [present, absent] }
      extensions:
        "{{ ansible_network_os }}":
          key: value
```
