### ISSUE TITLE
VRF definitions role

### ISSUE THREAD

**Issue by privateip** [ansible-network/network-proposals#3]
# Proposal: vrf_definitions role

*Author*: Peter Sprygada <@privateip>

*Date*: 2018-10-10

- Status: New
- Proposal type: role
- Targeted release: new
- Associated PR: none
- Estimated time to implement: 1 day

## Motivation
This proposal describe the implementation of a new resource role for managing VRF definitions in network device active configurations.  This role would replace the current `net_vrf` agnostic module that currently resides in Ansible core.

### Problems
The current platform agnostic module is difficult to maintain and even more challenging to extend.  By moving the module functionality to a role, platform specific implementations will be greatly simplified.

### Functions
- main.yaml
  noop by default
- configure.yaml
  Perform all configuration activities

### Model

```
vrf_definitions:
  operation: { default: merge, choices: [merge, replace, override] }
  config:
    "{{ vrf_name }}":
      description: { type: str }
      state: { default: present, choices: [present, absent] }
      extensions:
        "{{ ansible_network_os }}":
          key: value
```
