### ISSUE TITLE
BGP Role

### ISSUE THREAD

**Issue by NilashishC** [ansible-network/network-proposals#5]
# Proposal: BGP role

*Author*: Nilashish Chakraborty <@nilashishc> 

*Date*: 2018-12-06

- Status: New
- Proposal type: role
- Targeted release: new
- Associated PR: none
- Estimated time to implement: N/A

## Motivation
The BGP role provides a platform agnostic implementation to provide configuration management of the global BGP protocol settings on remote devices.

### Problems
By having this functionality as a role, platform specific implementations will be greatly simplified and easier to maintain given the huge variety of knobs that this protocol allows us to tweak.

### Functions
- main.yaml
  noop by default
- configure.yaml
  Perform all configuration activities

### Model
The below argument spec is *not* exhaustive. This is intended to give an overview of the parameters that this role would allow the user to tweak.
```yaml
bgp:
  operation: { default: merge, choices: [merge, replace, delete] }
  config:
    bgp_as: { type: int }
    router_id: { type: str }
    log_neighbor_changes: { type: bool }
    networks: { type: list, options=[route-map, network, mask, etc.] }
    neighbors: { type: list, options=[neighbor, remote-as, update-source, etc.] }
    address_family: { type: list, options=[afi, safi, neighbors, redistribute, networks, etc.] }
    extensions:
      "{{ ansible_network_os }}":
        key: value  
```
